config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'games/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/show.html.erb
<div class="show-warper" data-controller="battle">

  <div class="armies">

    <div class="army-good left">
      <div class="soldier-good">
      </div>
    </div>

    <div class="army-evil right">
      <div class="soldier-evil">
        <%# <%= image_tag("orc.png", width: 50, height: 50, :class => "img-fluid") %>
      </div>
    </div>

  </div>

</div>

<script> ScrollReveal().reveal('.soldier', { interval: 0.05, container: '.armies' } ); </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LotrSimBattle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/scrollreveal@4.0.0/dist/scrollreveal.min.js"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script>

  </script>
</html>

app/views/pages/home.html.erb
<div class="home-warper">

  <a class="btn-slice" href="<%=games_show_path%>">
    <div class="top"><span>FIGHT</span></div>
    <div class="bottom"><span>FIGHT</span></div>
  </a>

</div>